# Generated by Django 4.0.3 on 2022-03-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Hora', models.CharField(max_length=6)),
                ('Tipo_de_demanda', models.CharField(choices=[('1', 'Demanda de marca'), ('2', 'Demanda de linea'), ('3', 'Demanda de empresa'), ('4', 'Demanda global'), ('5', 'Demanda individual'), ('6', 'Demanda de segmento'), ('7', 'Demanda de mercado'), ('8', 'Demanda total')], default='1', max_length=1)),
                ('Rut_demandado', models.CharField(max_length=10)),
                ('Nombre_demandado', models.CharField(max_length=50)),
                ('Apellido_demandado', models.CharField(max_length=50)),
                ('Telefono_demandado', models.IntegerField()),
                ('Comuna_demandado', models.CharField(choices=[('1', 'Talcahuano'), ('2', 'Concepcion'), ('3', 'Chiguayante')], default='1', max_length=1)),
                ('Rut_demandante', models.CharField(max_length=10)),
                ('Nombre_demandante', models.CharField(max_length=50)),
                ('Apellido_demandante', models.CharField(max_length=50)),
                ('Telefono_demandante', models.IntegerField()),
                ('Comuna_demandante', models.CharField(choices=[('1', 'Talcahuano'), ('2', 'Concepcion'), ('3', 'Chiguayante')], default='1', max_length=1)),
                ('Detalle_demanda', models.CharField(max_length=500)),
            ],
        ),
    ]
