# Generated by Django 4.0.3 on 2022-03-18 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('legaltech_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='Fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
