# Generated by Django 4.0.3 on 2022-03-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltech_app', '0002_demanda_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='Comuna_demandado',
            field=models.CharField(choices=[('1', 'Talcahuano'), ('2', 'Concepcion'), ('3', 'Chiguayante')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='Comuna_demandante',
            field=models.CharField(choices=[('1', 'Talcahuano'), ('2', 'Concepcion'), ('3', 'Chiguayante')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='Tipo_de_demanda',
            field=models.CharField(choices=[('1', 'Demanda de marca'), ('2', 'Demanda de linea'), ('3', 'Demanda de empresa'), ('4', 'Demanda global'), ('5', 'Demanda individual'), ('6', 'Demanda de segmento'), ('7', 'Demanda de mercado'), ('8', 'Demanda total')], default=1, max_length=1),
        ),
    ]
