# Generated by Django 3.2.9 on 2022-04-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltech_app', '0003_alter_demanda_comuna_demandado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='Comuna_demandado',
            field=models.CharField(choices=[('1', 'Talcahuano'), ('2', 'Concepcion'), ('3', 'Chiguayante'), ('4', 'Hualpen')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='Comuna_demandante',
            field=models.CharField(choices=[('1', 'Talcahuano'), ('2', 'Concepcion'), ('3', 'Chiguayante'), ('4', 'Hualpen')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='Id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
