# Generated by Django 3.2.9 on 2022-04-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltech_app', '0004_auto_20220331_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
