# Generated by Django 4.0.1 on 2022-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltech_app', '0005_alter_demanda_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
